### ISSUE TITLE
DAC Supported List Link not Working

### ISSUE THREAD

**Issue by rjoel98** [balenalabs/balena-sound#450] opened 2021-05-19 16:45 UTC
Hey, I am searching a different issue that uses this block and realized that the supported list of DAC devices on the docs is not loading. I tried on a couple different devices and got the same result. I'll try to post the logs later when I get a chance. Thank you!

Here's the link to the docs: https://sound.balenalabs.io/docs/support/

And the direct link to the list: https://sound.balenalabs.io/docs/docs/audio-interfaces#dac-boards

**Comment by eiddor** [comment] 2021-05-24 16:09
See #448

**Comment by tmigone** [comment] 2021-05-24 16:56
Closing as it's a duplicate of #448

**Closed by tmigone** 2021-05-24 16:56 UTC
