### ISSUE TITLE
GitHub links in website header not working

### ISSUE THREAD

**Issue by tobi6112** [balenalabs/balena-sound#465] opened 2021-06-09 13:24 UTC
**Describe the problem**
GitHub links in the web page header on https://sound.balenalabs.io/ do not work.
The icon refers to the home page and the link on the version is applied as a relative link.

**Comment by tmigone** [comment] 2021-06-15 20:43
Closing as it's a duplicate of #448

**Closed by tmigone** 2021-06-15 20:43 UTC
Labels: bug
