### ISSUE TITLE
Connected but not playing any sound

### ISSUE THREAD

**Issue by bmugle0** [balenalabs/balena-sound#343] opened 2020-11-05 05:21 UTC
I have been trying to use it but even though my computer says it is connected it does not play any sound, and sometimes it just unconnects. When I try to play music, it says on the balena dash board: SBC decoding error (-2) and then the next row it says decoding error.

**Comment by shawaj** [comment] 2020-12-26 23:53
@bmugle0 how are you trying to play the sound? Is it Bluetooth or some other method?

And what file format are you trying to play?

**Comment by AlexProgrammerDE** [comment] 2020-12-29 13:27
This is related to Bluetooth and already reported. Duplicate of #62

**Closed by AlexProgrammerDE** 2020-12-29 13:27 UTC
Labels: bluetooth, bug, output
