### ISSUE TITLE
No sound volume control

### ISSUE THREAD

**Issue by Qu-Bi** [balenalabs/balena-sound#443] opened 2021-04-30 11:45 UTC
When I connect via UPnP I can control volume, but when I connecting via Bluetooth I can't control volume.

**Comment by JaragonCR** [comment] 2021-06-10 13:58
Is this a duplicate of https://github.com/balenalabs/balena-sound/issues/300 ?

I fixed mine (S21 Client) with the suggestion there

mount -o remount,rw /
systemctl edit --full bluetooth

edit to add the --plugin in this line

ExecStart=/usr/libexec/bluetooth/bluetoothd --experimental --plugin=a2dp

Save
Reboot

**Comment by tmigone** [comment] 2021-06-15 20:53
Yup duplicate of #300.

**Closed by tmigone** 2021-06-15 20:53 UTC
Labels: bug
