### ISSUE TITLE
Add Ks0314 keyestudio ReSpeaker 2-Mic Pi HAT V1.0 support

### ISSUE THREAD

**Issue by x0h01** [balenalabs/balena-sound#278] opened 2020-09-08 12:36 UTC
Please, review the possibility to add support for the following shield https://wiki.keyestudio.com/Ks0314_keyestudio_ReSpeaker_2-Mic_Pi_HAT_V1.0

**Comment by tmigone** [comment] 2020-09-22 19:46
Closing as it's a duplicate of #166

**Closed by tmigone** 2020-09-22 19:46 UTC
Labels: DAC
