### ISSUE TITLE
WM8960_Audio_HAT DAC board support

### ISSUE THREAD

**Issue by simonvanhove** [balenalabs/balena-sound#331] opened 2020-10-22 09:05 UTC
Hi,

is it possible to provide support for WM8960_Audio_HAT from Waveshare?
Here is their manual.

https://www.waveshare.com/w/upload/5/54/WM8960_Audio_HAT_User_Manual_EN.pdf

Greets,

Simon

**Comment by shawaj** [comment] 2020-12-27 00:29
Duplicate of #264

**Comment by AlexProgrammerDE** [comment] 2020-12-29 13:31
@shawaj may you tell me how to set a issue to a duplicate? If so please let me know.

**Closed by AlexProgrammerDE** 2020-12-29 13:31 UTC
Labels: duplicate

**Comment by shawaj** [comment] 2020-12-30 12:59
@AlexProgrammerDE hmm I am not actually sure how you do it. All I did was put a comment saying `Duplicate of ...` and it seemed to automatically set it like that?

It seems to be a standard feature of GitHub according to this doc - https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-duplicate-issues-and-pull-requests

**Comment by shawaj** [comment] 2021-01-07 22:32
Getting closer https://github.com/balenalabs/balena-sound/issues/264#issuecomment-756428272
